// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports, module) {
    var $, app, auth, conf, cookie, key, login, socket, socketIo;
    conf = module.config();
    socketIo = require('socketIo');
    cookie = require('cookie');
    $ = require('$');
    app = require('app');
    socket = void 0;
    key = void 0;
    window.onbeforeunload = function() {
      $.cookie('key', '');
      return "Logged out, please close this tab.";
    };
    auth = function() {
      key = $.cookie('key');
      if (key != null) {
        console.log("Auth: try auth with key: " + key);
        return socket.emit('auth', key);
      } else {
        console.log("Auth: !key, try to login");
        return login();
      }
    };
    login = function() {
      var presentDialog,
        _this = this;
      presentDialog = function() {
        ($('DIV#loginDialog')).modal();
        return ($('DIV#loginDialogSubSlab')).css({
          display: 'block'
        });
      };
      if (0 === ($('DIV#loginDialog')).length) {
        return $.get('/vendor/loginDialog.html', function(html) {
          ($('BODY')).append(html);
          presentDialog();
          ($('DIV#loginDialog')).on('shown.bs.modal', function() {
            return ($('INPUT#inputEmail')).focus();
          });
          return ($('BUTTON#loginDialogLogin')).click(function() {
            socket.emit('login', ($('INPUT#inputEmail')).val(), ($('INPUT#inputPassword')).val());
            return ($('BUTTON#loginDialogClose')).trigger('click');
          });
        });
      } else {
        return presentDialog();
      }
    };
    module.exports.getSocket = function() {
      return socket;
    };
    module.exports.init = function() {
      socket = io.connect("" + document.location.protocol + "//" + document.location.hostname + ":" + document.location.port);
      socket.on('connect', function() {
        if (conf.auth) {
          return auth();
        } else {
          return app();
        }
      });
      socket.on('disconnect', function() {
        console.log('SOCK: disconnect');
        return ($('DIV#loginDialogSubSlab')).css({
          display: 'block'
        });
      });
      socket.on('login', function() {
        return login();
      });
      socket.on('userName', function(userName) {
        console.log("received username: " + userName);
        ($('DIV#loginDialogSubSlab')).css({
          display: 'none'
        });
        return app();
      });
      return socket.on('key', function(key) {
        console.log("Auth: received key: " + key);
        $.cookie('key', key);
        ($('INPUT#inputEmail')).val('');
        ($('INPUT#inputPassword')).val('');
        if (app.loggedIn != null) {
          return app.loggedIn();
        }
      });
    };
    return void 0;
  });

}).call(this);
